name: CD

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'           # Push events to every tag not containing /
  workflow_dispatch:

jobs:
  cargo_checks:
    name: Cargo Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/rust_toolchain/
      - name: Check formatting
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --features ssr --tests -- -D warnings
      - name: Install Cargo Rdme
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-rdme
      - name: Check if the README is up to date.
        run: cargo rdme --check
      - name: Run tests
        run: cargo test --features ssr

  test_examples:
    name: Test Examples
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - basic
          - chat
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/rust_toolchain/
      - name: Build example ${{ matrix.example }}
        run: |
          cd ${{ github.workspace }}/examples/${{ matrix.example }}/
          cargo build
        shell: bash

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ cargo_checks, test_examples ]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/rust_toolchain/
      - name: Publish crate
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_TOKEN }}

      - uses: CSchoel/release-notes-from-changelog@v1
      - name: Create Release using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create
          -d
          -F RELEASE.md
          -t "Version $RELEASE_VERSION"
          ${GITHUB_REF#refs/*/}
